# Install the apt prerequisites
# addons:
#  apt:
#    packages:
#      - python-pygments
# Clean and don't fail
install:
  - rm -rf public || exit 0
# Build the website
script:
  - binary/hugo --theme=even
  # Create a CNAME file which maps your site to your custom domain
  - echo 'devtian.me' > public/CNAME
# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master